title: Javier Blog
description: DevOps, DevSecOps, Hashicorp Suite, Rancher, Docker, Kubernetes.
show_downloads: false

baseurl: "/javier-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://javierlimon.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Javier Limon
image: /thumbnail-jumbo.png
#twitter:
#  username: lorepirri

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: javierblog-com
